# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharajinnyserverapi', '0004_likes_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='mass_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
