# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharajinnyserverapi', '0006_auto_20180103_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mass_post',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'upload'),
            preserve_default=False,
        ),
    ]
