# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharajinnyserverapi', '0007_auto_20180104_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='status',
        ),
        migrations.AlterField(
            model_name='likes',
            name='photo',
            field=models.FileField(upload_to=b'upload'),
        ),
    ]
